### ISSUE TITLE
Project 5 the clock 

### ISSUE THREAD

**Issue by glynnmason** [ArmstrongSubero/PIC16-Projects#1]
I have bought your book and down loaded the code for the touch screen clock when I open the code in mplabx and try to compile it I get errors I have used xc8 v1.35 v1.38 v1.41 and still get errors can you have a look and see what could be the problem thanks 

this is the errors hope you can help 

make -f nbproject/Makefile-default.mk SUBPROJECTS= .build-conf
make[1]: Entering directory 'C:/Users/Glynn/MPLABXProjects/16F/16F1717/New folder/P05_Clock.X'
make  -f nbproject/Makefile-default.mk dist/default/production/P05_Clock.X.production.hex
make[2]: Entering directory 'C:/Users/Glynn/MPLABXProjects/16F/16F1717/New folder/P05_Clock.X'
"C:\Program Files (x86)\Microchip\xc8\v1.35\bin\xc8.exe" --pass1  --chip=16F1717 -Q -G  --double=24 --float=24 --opt=default,+asm,+asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -P -N255 --warn=-3 --asmlist -DXPRJ_default=default  --summary=default,-psect,-class,+mem,-hex,-file --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-osccal,-resetbits,-download,-stackcall,+clib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"    -obuild/default/production/16F1717_Internal.p1  16F1717_Internal.c 
"C:\Program Files (x86)\Microchip\xc8\v1.35\bin\xc8.exe" --pass1  --chip=16F1717 -Q -G  --double=24 --float=24 --opt=default,+asm,+asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -P -N255 --warn=-3 --asmlist -DXPRJ_default=default  --summary=default,-psect,-class,+mem,-hex,-file --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-osccal,-resetbits,-download,-stackcall,+clib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"    -obuild/default/production/I2C.p1  I2C.c 
"C:\Program Files (x86)\Microchip\xc8\v1.35\bin\xc8.exe" --pass1  --chip=16F1717 -Q -G  --double=24 --float=24 --opt=default,+asm,+asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -P -N255 --warn=-3 --asmlist -DXPRJ_default=default  --summary=default,-psect,-class,+mem,-hex,-file --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-osccal,-resetbits,-download,-stackcall,+clib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"    -obuild/default/production/Main.p1  Main.c 
"C:\Program Files (x86)\Microchip\xc8\v1.35\bin\xc8.exe" --pass1  --chip=16F1717 -Q -G  --double=24 --float=24 --opt=default,+asm,+asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -P -N255 --warn=-3 --asmlist -DXPRJ_default=default  --summary=default,-psect,-class,+mem,-hex,-file --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-osccal,-resetbits,-download,-stackcall,+clib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"    -obuild/default/production/ds1302.p1  ds1302.c 
"C:\Program Files (x86)\Microchip\xc8\v1.35\bin\xc8.exe" --pass1  --chip=16F1717 -Q -G  --double=24 --float=24 --opt=default,+asm,+asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -P -N255 --warn=-3 --asmlist -DXPRJ_default=default  --summary=default,-psect,-class,+mem,-hex,-file --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-osccal,-resetbits,-download,-stackcall,+clib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"    -obuild/default/production/oled.p1  oled.c 
"C:\Program Files (x86)\Microchip\xc8\v1.35\bin\xc8.exe" --pass1  --chip=16F1717 -Q -G  --double=24 --float=24 --opt=default,+asm,+asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -P -N255 --warn=-3 --asmlist -DXPRJ_default=default  --summary=default,-psect,-class,+mem,-hex,-file --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-osccal,-resetbits,-download,-stackcall,+clib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"    -obuild/default/production/EUSART.p1  EUSART.c 
"C:\Program Files (x86)\Microchip\xc8\v1.35\bin\xc8.exe" --pass1  --chip=16F1717 -Q -G  --double=24 --float=24 --opt=default,+asm,+asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -P -N255 --warn=-3 --asmlist -DXPRJ_default=default  --summary=default,-psect,-class,+mem,-hex,-file --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-osccal,-resetbits,-download,-stackcall,+clib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"    -obuild/default/production/setup.p1  setup.c 
"C:\Program Files (x86)\Microchip\xc8\v1.35\bin\xc8.exe" --pass1  --chip=16F1717 -Q -G  --double=24 --float=24 --opt=default,+asm,+asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -P -N255 --warn=-3 --asmlist -DXPRJ_default=default  --summary=default,-psect,-class,+mem,-hex,-file --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-osccal,-resetbits,-download,-stackcall,+clib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"    -obuild/default/production/touchscreen.p1  touchscreen.c 
Main.c:105: warning: (346) declaration of "min1" hides outer declaration
Main.c:163: warning: (359) illegal conversion between pointer types
pointer to const unsigned char -> pointer to unsigned char
Main.c:187: warning: (359) illegal conversion between pointer types
pointer to const unsigned char -> pointer to unsigned char
Main.c:211: warning: (359) illegal conversion between pointer types
pointer to const unsigned char -> pointer to unsigned char
Main.c:237: warning: (359) illegal conversion between pointer types
pointer to const unsigned char -> pointer to unsigned char
Main.c:257: warning: (359) illegal conversion between pointer types
pointer to const unsigned char -> pointer to unsigned char
Main.c:288: warning: (359) illegal conversion between pointer types
pointer to const unsigned char -> pointer to unsigned char
Main.c:290: warning: (359) illegal conversion between pointer types
pointer to const unsigned char -> pointer to unsigned char
Main.c:297: warning: (359) illegal conversion between pointer types
pointer to const unsigned char -> pointer to unsigned char
Main.c:299: warning: (359) illegal conversion between pointer types
pointer to const unsigned char -> pointer to unsigned char
Main.c:442: warning: (359) illegal conversion between pointer types
pointer to const unsigned char -> pointer to unsigned char
Main.c:445: warning: (359) illegal conversion between pointer types
pointer to const unsigned char -> pointer to unsigned char
Main.c:448: warning: (359) illegal conversion between pointer types
pointer to const unsigned char -> pointer to unsigned char
ds1302.c:161: error: (195) expression syntax
(908) exit status = 1
nbproject/Makefile-default.mk:180: recipe for target 'build/default/production/ds1302.p1' failed
oled.c:304: warning: (359) illegal conversion between pointer types
pointer to const unsigned char -> pointer to unsigned char
oled.c:324: warning: (359) illegal conversion between pointer types
make[2]: *** [build/default/production/ds1302.p1] Error 1
make[2]: *** Waiting for unfinished jobs....
pointer to const unsigned char -> pointer to unsigned char
EUSART.c:110: warning: (346) declaration of "i" hides outer declaration
setup.c:75: warning: (361) function declared implicit int
setup.c:86: warning: (359) illegal conversion between pointer types
pointer to const unsigned char -> pointer to unsigned char
make[1]: *** [.build-conf] Error 2
make: *** [.build-impl] Error 2
make[2]: Leaving directory 'C:/Users/Glynn/MPLABXProjects/16F/16F1717/New folder/P05_Clock.X'
nbproject/Makefile-default.mk:84: recipe for target '.build-conf' failed
make[1]: Leaving directory 'C:/Users/Glynn/MPLABXProjects/16F/16F1717/New folder/P05_Clock.X'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed

BUILD FAILED (exit value 2, total time: 3s)

**Comment by ArmstrongSubero** [comment]
Dear Glynn,

Thanks for reaching out! I think it could be an error with the C version
you are using (is it C89?), or it could just be the compiler messing up(try
restarting the IDE or a reinstall of the compiler) here is a version that I
can verify compiles with MPLABX v5.15 and XC8 v1.38. I put it in a zip
together with a screenshot verifying compilation. Let me know if this works!

Cordially,
Armstrong Subero

**Comment by glynnmason** [comment]
where is the zip file its not there ?

**Comment by ArmstrongSubero** [comment]
Hi Glynn,

Reattaching.

Cordially,

Armstrong Subero

**Comment by glynnmason** [comment]
it still don't work it says   Whoops! That unsubscribe link isn't valid for your account

**Comment by glynnmason** [comment]
HI Armstrong

I have reopened mplabx and I am getting less errors using xc8 v1.38


make -f nbproject/Makefile-default.mk SUBPROJECTS= .build-conf
make[1]: Entering directory 'C:/Users/Glynn/MPLABXProjects/16F/16F1717/P05_Clock.X'
make  -f nbproject/Makefile-default.mk dist/default/production/P05_Clock.X.production.hex
make[2]: Entering directory 'C:/Users/Glynn/MPLABXProjects/16F/16F1717/P05_Clock.X'
"C:\Program Files (x86)\Microchip\xc8\v1.38\bin\xc8.exe" --pass1  --chip=16F1717 -Q -G  --double=24 --float=24 --opt=+asm,+asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -P -N255 --warn=-3 --asmlist -DXPRJ_default=default  --summary=default,-psect,-class,+mem,-hex,-file --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-osccal,-resetbits,-download,-stackcall,+clib   --output=-mcof,+elf:multilocs --stack=compiled:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"     -obuild/default/production/ds1302.p1 ds1302.c 
ds1302.c:161: error: (195) expression syntax
(908) exit status = 1
nbproject/Makefile-default.mk:186: recipe for target 'build/default/production/ds1302.p1' failed
make[2]: Leaving directory 'C:/Users/Glynn/MPLABXProjects/16F/16F1717/P05_Clock.X'
nbproject/Makefile-default.mk:90: recipe for target '.build-conf' failed
make[1]: Leaving directory 'C:/Users/Glynn/MPLABXProjects/16F/16F1717/P05_Clock.X'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed
make[2]: *** [build/default/production/ds1302.p1] Error 1
make[1]: *** [.build-conf] Error 2
make: *** [.build-impl] Error 2

BUILD FAILED (exit value 2, total time: 1s)

**Comment by glynnmason** [comment]
HI Armstrong

I have just sorted it there is a full stop on the line of code that was making the error 
thanks for your help any way are you going to-do another book one thing I am interested  in is rtos going to look into it my self soon 


glynn mason

**Comment by ArmstrongSubero** [comment]
Hi Glynn,

Glad to know you got through. Actually I'm working on a book on data
structures and algorithms right now. My 3rd book I may look into doing
something on real time and safety critical systems.

Cordially,
Armstrong Subero

**Comment by glynnmason** [comment]
Hi Armstrong
Thats sounds intresting , ive not got the clock project working for some reason the display isn't showing anything other than whats been created in the nextion editor have a missed something when creating the display that could make it not work ,you don't go in to much detail in your book about that part of it so haviong to learn how to edit the display iam wondering if something is missing in your book or have i missed something ive created both pages how you have shown wonderign if the labels are wronge ,if you can't help i will just keep tring diffrent things in a hope of getting it to work 
thanks 
glynn mason

**Comment by ArmstrongSubero** [comment]
Hi Glynn,

I didn't realize it was so obscure. I aould have added more steps, but I
had a size and time limit to work with.

The process basically involves setting up your display GUI and sending
information via UART from the display, which is then parsed by the
microcontroller which communicates with the RTC chip, and sends data back
to the display.

If you have problems understanding it trt these steps.

First create a single button on the display, and use it to turn on an LED
on the microcontroller.

Then verify you can read the time from the RTC with the uC apart from the
touch display.

Work on laying out your GUI and ensure you can get the uC to change the
numbers on the display.

Finally use the code in the book to put everything together.

I hope this helps, just take the process step by step.

Cordially,

Arnstrong Subero

**Comment by glynnmason** [comment]
Hi Armstrong 

ok my level using c is limited and also I wouldn't know where to start writing code for even just lighting an led from the display its going to take quite a while ,I forgot to say I've check my wiring to make Shure I've got the right port and the tx and rx are the right way round ,I did display some values from a potentiometer  but that was with an Arduino and somebody's code of a YouTube video and it worked so I know the display works that was about six months ago , thanks for you help I will just have to try and work out why it's not working 


glynn mason
